/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ABID
 */
import javax.swing.JOptionPane;
public class CetakKarcis extends javax.swing.JPanel {

    /**
     * Creates new form CetakKarcis
     */
    public CetakKarcis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariData = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStruk = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(950, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Cetak Karcis");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(415, 415, 415))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Plat Nomer");

        txtCariData.addActionListener(this::txtCariDataActionPerformed);

        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        txtStruk.setColumns(20);
        txtStruk.setRows(5);
        jScrollPane1.setViewportView(txtStruk);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari))
                    .addComponent(jScrollPane1))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnKembali))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariDataActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String platCari = txtCariData.getText().trim();

    if (platCari.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ketik plat nomor yang mau dicari dulu lek!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String sql = "SELECT * FROM kendaraan WHERE plat_nomor = ? ORDER BY tanggal_masuk DESC LIMIT 1";

    try {
        java.sql.Connection conn = Koneksi.getConnection();
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, platCari);
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String kode = rs.getString("kode_tarif");
            String plat = rs.getString("plat_nomor");
            String jenis = rs.getString("jenis_kendaraan");
            String tgl = rs.getString("tanggal_masuk");
            String jam = rs.getString("waktu_masuk");
            int tarif = rs.getInt("tarif");

            if (plat != null && plat.matches("^[A-Z]{1,2}\\d{1,4}[A-Z]{1,3}$")) {
                plat = plat.replaceAll("^([A-Z]{1,2})(\\d{1,4})([A-Z]{1,3})$", "$1 $2 $3");
            }

            StringBuilder sb = new StringBuilder();
            sb.append("\t\t--- PARKSMART STATION ---\n");
            sb.append("\tJl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat\n");
            sb.append("\tTelp. +6229-123456\n");
            sb.append("==================================================\n");
            sb.append("========= KARCIS TANDA MASUK PARKIR =========\n");
            sb.append(" Kode Tiket\t: ").append(kode).append("\n");
            sb.append(" Plat Nomer\t: ").append(plat).append("\n");
            sb.append(" Jenis Kendaraan\t: ").append(jenis.toUpperCase()).append("\n");
            sb.append(" Tanggal\t\t: ").append(tgl).append("\n");
            sb.append(" Jam Masuk\t: ").append(jam).append("\n");
            sb.append(" Biaya\t\t: Rp. ").append(tarif).append(" /Jam\n");
            sb.append("==================================================\n");
            sb.append("        Demi Kenyamanan dan Keamanan,\n");
            sb.append("     Mohon Jangan Meninggalkan Karcis Ini\n");
            sb.append("==================================================\n");

            txtStruk.setText(sb.toString());

        } else {
            JOptionPane.showMessageDialog(this, "Data kendaraan dengan plat " + platCari + " tidak ditemukan lek!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtStruk.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal cari data lek: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if (txtStruk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Belum ada data karcis yang dicari lek!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            java.text.MessageFormat header = new java.text.MessageFormat("Karcis ParkSmart Masuk");
            java.text.MessageFormat footer = new java.text.MessageFormat("Halaman {0}");

            boolean complete = txtStruk.print(header, footer, true, null, null, true);

            if (complete) {
                JOptionPane.showMessageDialog(this, "Karcis sukses diproses untuk PDF/Printer!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Gagal memproses cetak PDF lek: " + e.getMessage(), "Printer Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        HalamanUtama hu = new HalamanUtama("");
        hu.setVisible(true);

        javax.swing.JFrame frameInduk = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frameInduk != null) {
            frameInduk.dispose();
        }
    }//GEN-LAST:event_btnKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextArea txtStruk;
    // End of variables declaration//GEN-END:variables
}
