/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ABID
 */
import javax.swing.JOptionPane;
public class CetakKarcis extends javax.swing.JPanel {
    private String petugasAktif = "";
    /**
     * Creates new form CetakKarcis
     */
    public CetakKarcis() {
        initComponents();
    }
    
    public CetakKarcis(String kodeOtomatis, String namaPetugas) {
        initComponents();
        this.petugasAktif = namaPetugas;
        txtCariData.setText(kodeOtomatis);
        btnCariKodeActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariData = new javax.swing.JTextField();
        btnCariKode = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStruk = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(950, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(524, 33));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Cetak Karcis");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(415, 415, 415))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Kode Karcis");

        txtCariData.addActionListener(this::txtCariDataActionPerformed);

        btnCariKode.setBackground(new java.awt.Color(204, 204, 255));
        btnCariKode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCariKode.setText("Cari");
        btnCariKode.addActionListener(this::btnCariKodeActionPerformed);

        btnCetak.setBackground(new java.awt.Color(204, 204, 255));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        btnKembali.setBackground(new java.awt.Color(204, 204, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        txtStruk.setColumns(20);
        txtStruk.setRows(5);
        jScrollPane1.setViewportView(txtStruk);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKembali))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCariKode))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariKode))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnKembali))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariDataActionPerformed

    private void btnCariKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKodeActionPerformed
        // TODO add your handling code here:
        String kodeCari = txtCariData.getText().trim().toUpperCase().replace(" ", "");

        if (kodeCari.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ketik Kode Karcis yang mau dicari!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (kodeCari.length() == 6 && !kodeCari.contains("-")) {
            kodeCari = kodeCari.substring(0, 2) + "-" + kodeCari.substring(2);
        }

        String sql = "SELECT * FROM data_kendaraan WHERE kode_tarif = ?";

        try {
            java.sql.Connection conn = Koneksi.getConnection();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, kodeCari);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String kode = rs.getString("kode_tarif");
                String jenis = rs.getString("jenis_kendaraan");
                String tgl = rs.getString("tanggal_masuk");
                String jam = rs.getString("jam_masuk");
                int tarif = rs.getInt("tarif");

                StringBuilder sb = new StringBuilder();
                sb.append("\t                             --- PARKSMART STATION ---\n");
                sb.append("\t                Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat\n");
                sb.append("\t\t             Telp. +6229-123456\n");
                sb.append("\t==================================================\n");
                sb.append("\t============ KARCIS TANDA MASUK PARKIR ============\n");
                sb.append("\tKode Tiket\t\t: ").append(kode).append("\n");
                sb.append("\tJenis Kendaraan\t: ").append(jenis.toUpperCase()).append("\n");
                sb.append("\tTanggal\t\t: ").append(tgl).append("\n");
                sb.append("\tJam Masuk\t\t: ").append(jam).append("\n");
                sb.append("\tBiaya\t\t: Rp. ").append(tarif).append(" /Jam\n");
                sb.append("\t==================================================\n");
                sb.append("\t\t   Demi Kenyamanan dan Keamanan,\n");
                sb.append("\t                       Mohon Tidak Meninggalkan Karcis Ini\n");
                 sb.append("\t          Segala Bentuk Kehilangan Bukan Tanggung Jawab Kami\n");
                sb.append("\t==================================================\n");

                txtStruk.setText(sb.toString());

            } else {
                JOptionPane.showMessageDialog(this, "Kode Karcis " + kodeCari + " tidak ditemukan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                txtStruk.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal cari data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCariKodeActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if (txtStruk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Belum ada data karcis yang dicari!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            java.text.MessageFormat header = new java.text.MessageFormat("Karcis ParkSmart Masuk");
            java.text.MessageFormat footer = new java.text.MessageFormat("Halaman {0}");

            boolean complete = txtStruk.print(header, footer, true, null, null, true);

            if (complete) {
                JOptionPane.showMessageDialog(this, "Karcis sukses diproses untuk PDF/Printer!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Gagal memproses cetak PDF: " + e.getMessage(), "Printer Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        HalamanUtama hu = new HalamanUtama(this.petugasAktif);
        hu.setVisible(true);

        javax.swing.JFrame frameInduk = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frameInduk != null) {
            frameInduk.dispose();
        }
    }//GEN-LAST:event_btnKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariKode;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextArea txtStruk;
    // End of variables declaration//GEN-END:variables
}
