/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Dearis Mahendra
 */
public class DetailLogMasuk extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailLogMasuk.class.getName());
    
    private String kodeTarifTerima;
    /**
     * Creates new form DetailLog
     */
    public DetailLogMasuk(java.awt.Frame parent, boolean modal, String kodeCari) {
        super(parent, modal);
        initComponents();
        
        this.kodeTarifTerima = kodeCari;
        ambilDataLengkap();
    }
    
    private void ambilDataLengkap() {
    String sql = "SELECT * FROM data_kendaraan WHERE kode_tarif = ?";
    
    try {
        java.sql.Connection conn = Koneksi.getConnection();
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, kodeTarifTerima);
        java.sql.ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            String tglMasukDb = rs.getString("tanggal_masuk");
            String waktuMasukStr = rs.getString("waktu_masuk");
                try {
                    java.util.Date dateMasuk = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tglMasukDb);
                    String tglMasukFix = new java.text.SimpleDateFormat("dd MMM yyyy").format(dateMasuk);
                    lblWaktuMasuk.setText(tglMasukFix + " - " + waktuMasukStr + " | Oleh " + rs.getString("petugas_jaga"));
                } catch (Exception e) {
                    lblWaktuMasuk.setText(tglMasukDb + " - " + waktuMasukStr + " | Oleh " + rs.getString("petugas_jaga"));
                }
            
            lblKode.setText(kodeTarifTerima);
            
            String platDb = rs.getString("plat_nomor");
            String platFix = platDb.replaceAll("^([A-Z]{1,2})(\\d+)([A-Z]{1,3})$", "$1 $2 $3");
            lblPlat.setText(platFix + " - " + rs.getString("jenis_kendaraan"));
            
            lblJenisKen.setText(rs.getString("jenis_kendaraan"));
            lblWarna.setText(rs.getString("warna_kendaraan"));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Data kendaraan aktif tidak ditemukan lek!");
        }
        
        rs.close();
        ps.close();
    } catch (Exception e) {
        System.out.println("Gagal load data detail masuk lek: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblWaktuMasuk = new javax.swing.JLabel();
        lblStatusKendaraan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblPlat = new javax.swing.JLabel();
        lblJenisKen = new javax.swing.JLabel();
        lblWarna = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Detail Log Aktivitas");

        jButton1.setFont(new java.awt.Font("Broadway", 1, 12)); // NOI18N
        jButton1.setText("<");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo P.png"))); // NOI18N
        jLabel3.setText("ParkSmart");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 43, -1, -1));

        lblWaktuMasuk.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblWaktuMasuk.setText("21 Jun 2026 - 21:37:33 | Oleh Dearis");
        jPanel1.add(lblWaktuMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        lblStatusKendaraan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatusKendaraan.setText("Kendaraan Masuk");
        jPanel1.add(lblStatusKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 101, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 123, 405, 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kode Tarif");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Plat Nomer");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Jenis Kendaraan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Warna Kendaraan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        lblKode.setText("MT-7270");
        jPanel1.add(lblKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        lblPlat.setText("B 1234 ABC");
        jPanel1.add(lblPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        lblJenisKen.setText("Motor");
        jPanel1.add(lblJenisKen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        lblWarna.setText("Kuning");
        jPanel1.add(lblWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ParkSmart.jpg"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 630, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DetailLogMasuk dialog = new DetailLogMasuk(new javax.swing.JFrame(), true, "MT-7270");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblJenisKen;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblPlat;
    private javax.swing.JLabel lblStatusKendaraan;
    private javax.swing.JLabel lblWaktuMasuk;
    private javax.swing.JLabel lblWarna;
    // End of variables declaration//GEN-END:variables
}
