/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ABID
 */
public class FiturUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FiturUtama.class.getName());

    /**
     * Creates new form FiturUtama
     */
    private String petugasLogin;
    public FiturUtama(String namaPetugas) {
        initComponents();
        this.petugasLogin = namaPetugas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUtama = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnAktivitas = new javax.swing.JButton();
        pnlKonten = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUtama.setText("Halaman Utama");
        btnUtama.addActionListener(this::btnUtamaActionPerformed);
        getContentPane().add(btnUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnAdmin.setText("Mode admin");
        btnAdmin.addActionListener(this::btnAdminActionPerformed);
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 100, -1));

        btnAktivitas.setText("Aktivitas");
        btnAktivitas.addActionListener(this::btnAktivitasActionPerformed);
        getContentPane().add(btnAktivitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 100, -1));

        pnlKonten.setBackground(new java.awt.Color(204, 204, 204));
        pnlKonten.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlKonten, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 950, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Desain_tanpa_judul.jpg.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtamaActionPerformed
        // TODO add your handling code here:
        halamanUtama utama = new halamanUtama(this.petugasLogin); 
    
        // 3. Sisa kode kamu ke bawah buat nampilin panelnya biarkan tetap seperti aslinya
        utama.setVisible(true);
        pnlKonten.add(utama);
        pnlKonten.revalidate();
        pnlKonten.repaint();
    }//GEN-LAST:event_btnUtamaActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnAktivitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktivitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAktivitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FiturUtama("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAktivitas;
    private javax.swing.JButton btnUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlKonten;
    // End of variables declaration//GEN-END:variables
}
