/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ABID
 */
public class HalamanUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HalamanUtama.class.getName());

    /**
     * Creates new form FiturUtama
     */
    private String petugasLogin;
    public HalamanUtama(String namaPetugas) {
        initComponents();
        this.petugasLogin = namaPetugas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMasuk = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnKeuangan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnAktivitas = new javax.swing.JButton();
        btnKeuangan1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlKonten = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMasuk.setBackground(new java.awt.Color(204, 204, 255));
        btnMasuk.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnMasuk.setText("Parkir Masuk");
        btnMasuk.addActionListener(this::btnMasukActionPerformed);
        getContentPane().add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 18, -1, 40));

        btnCetak.setBackground(new java.awt.Color(204, 204, 255));
        btnCetak.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnCetak.setText("Cetak Karcis");
        btnCetak.addActionListener(this::btnCetakActionPerformed);
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 18, -1, 40));

        btnKeuangan.setBackground(new java.awt.Color(204, 204, 255));
        btnKeuangan.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnKeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Logout.png"))); // NOI18N
        btnKeuangan.setText("Logout");
        btnKeuangan.addActionListener(this::btnKeuanganActionPerformed);
        getContentPane().add(btnKeuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 18, -1, 40));

        btnKeluar.setBackground(new java.awt.Color(204, 204, 255));
        btnKeluar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnKeluar.setText("Parkir Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 18, -1, 40));

        btnAktivitas.setBackground(new java.awt.Color(204, 204, 255));
        btnAktivitas.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnAktivitas.setText("Aktivitas");
        btnAktivitas.addActionListener(this::btnAktivitasActionPerformed);
        getContentPane().add(btnAktivitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 18, -1, 40));

        btnKeuangan1.setBackground(new java.awt.Color(204, 204, 255));
        btnKeuangan1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnKeuangan1.setText("Laporan");
        btnKeuangan1.addActionListener(this::btnKeuangan1ActionPerformed);
        getContentPane().add(btnKeuangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 18, -1, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/W Park_Smart.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, -50, 530, 190));

        pnlKonten.setBackground(new java.awt.Color(204, 204, 204));
        pnlKonten.setLayout(new java.awt.CardLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Coildisc (2).png"))); // NOI18N
        pnlKonten.add(jLabel2, "card2");

        getContentPane().add(pnlKonten, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 950, 390));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Desain_tanpa_judul.jpg.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        pnlKonten.removeAll();
        
        ParkirMasuk masuk = new ParkirMasuk(this.petugasLogin); 
        pnlKonten.add(masuk);
        
        pnlKonten.revalidate();
        pnlKonten.repaint();
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        pnlKonten.removeAll();
        
        CetakKarcis cetak = new CetakKarcis();
        pnlKonten.add(cetak);
      
        pnlKonten.revalidate();
        pnlKonten.repaint();
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeuanganActionPerformed
        // TODO add your handling code here:
        pnlKonten.removeAll();
    
        Laporan pnlLaporan = new Laporan();

        pnlLaporan.setSize(pnlKonten.getWidth(), pnlKonten.getHeight());

        pnlKonten.add(pnlLaporan);

        pnlKonten.repaint();
        pnlKonten.revalidate();
    }//GEN-LAST:event_btnKeuanganActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        ParkirKeluar keluar = new ParkirKeluar();
    
        pnlKonten.removeAll();

        pnlKonten.add(keluar);

        pnlKonten.repaint();
        pnlKonten.revalidate();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnAktivitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktivitasActionPerformed
        // TODO add your handling code here:
        pnlKonten.removeAll();
    
        LogAktivitas pnlLog = new LogAktivitas();

        pnlLog.setSize(pnlKonten.getWidth(), pnlKonten.getHeight());

        pnlKonten.add(pnlLog);
        pnlKonten.repaint();
        pnlKonten.revalidate();
    }//GEN-LAST:event_btnAktivitasActionPerformed

    private void btnKeuangan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeuangan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeuangan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HalamanUtama("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktivitas;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKeuangan;
    private javax.swing.JButton btnKeuangan1;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel pnlKonten;
    // End of variables declaration//GEN-END:variables
}
