/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Dearis Mahendra
 */
import javax.swing.JOptionPane;
public class KendaraanMasuk extends javax.swing.JPanel {

    /**
     * Creates new form halamanUtama
     */
    public KendaraanMasuk(String namaPetugas) {
        initComponents();
        
        java.time.LocalDate date = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formatTanggal = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
        txtTgl.setText(date.format(formatTanggal));
        txtTgl.setEditable(false); 

        java.time.LocalTime time = java.time.LocalTime.now();
        java.time.format.DateTimeFormatter formatJam = java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss");
        txtJam.setText(time.format(formatJam));
        txtJam.setEditable(false);
        
        cbPetugas.setSelectedItem(namaPetugas);
        loadTable();
    }
    
    private String kodeTarifAcak(String jenisKendaraan) {
        StringBuilder sb = new StringBuilder();
        java.util.Random random = new java.util.Random();

        if (jenisKendaraan.equalsIgnoreCase("MOTOR")) {
            sb.append("MT-");
        } else if (jenisKendaraan.equalsIgnoreCase("MOBIL")) {
            sb.append("MB-");
        } else {
            sb.append("TRF-");
        }

        int angka = 1000 + random.nextInt(9000);
        sb.append(angka);

        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPlat = new javax.swing.JTextField();
        txtWarna = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        txtTlp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kendaraanMotor = new javax.swing.JRadioButton();
        txtJam = new javax.swing.JTextField();
        txtTarif = new javax.swing.JTextField();
        kendaraanMobil = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        cbPetugas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(950, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Tarif", "No Tlp", "Plat Nomer", "Jenis Kendaraan", "Warna Kendaraan", "Tanggal Masuk", "Jam Masuk", "Tarif", "Nama Petugas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 190, 960, 210));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("No Tlp");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Plat Nomer");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Jenis Kendaraan");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Warna Kendaraan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal Masuk");

        txtWarna.addActionListener(this::txtWarnaActionPerformed);

        txtTgl.addActionListener(this::txtTglActionPerformed);

        txtTlp.addActionListener(this::txtTlpActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jam Masuk");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tarif");

        buttonGroup1.add(kendaraanMotor);
        kendaraanMotor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kendaraanMotor.setText("Motor");
        kendaraanMotor.addActionListener(this::kendaraanMotorActionPerformed);

        txtJam.addActionListener(this::txtJamActionPerformed);

        txtTarif.addActionListener(this::txtTarifActionPerformed);

        buttonGroup1.add(kendaraanMobil);
        kendaraanMobil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kendaraanMobil.setText("Mobil");
        kendaraanMobil.addActionListener(this::kendaraanMobilActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Nama Petugas");

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Tambahkan");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        cbPetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Petugas", "Dearis", "Khabid", "Rohman" }));
        cbPetugas.addActionListener(this::cbPetugasActionPerformed);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Input Data Kendaraan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btnHapus.setBackground(new java.awt.Color(204, 204, 255));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Clear");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnKembali.setBackground(new java.awt.Color(204, 204, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kendaraanMotor)
                                .addGap(18, 18, 18)
                                .addComponent(kendaraanMobil))
                            .addComponent(txtTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKembali)
                            .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave))
                .addContainerGap(94, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kendaraanMotor)
                    .addComponent(kendaraanMobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali)
                    .addComponent(btnSave)
                    .addComponent(btnHapus))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTlpActionPerformed

    private void txtTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifActionPerformed

    private void txtWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarnaActionPerformed

    private void kendaraanMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kendaraanMobilActionPerformed
        // TODO add your handling code here:
        txtTarif.setText("5000");
        txtTarif.setEditable(false);
    }//GEN-LAST:event_kendaraanMobilActionPerformed

    private void txtTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglActionPerformed

    private void txtJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String platNomor = txtPlat.getText().trim();
        String warna = txtWarna.getText().trim();
        String telp = txtTlp.getText().trim();
        String tanggalMasuk = txtTgl.getText();
        String waktuMasuk = txtJam.getText();
        
        String pilihPetugas = cbPetugas.getSelectedItem().toString();

        String jenisKendaraan = "";
        if (kendaraanMobil.isSelected()) {
            jenisKendaraan = "MOBIL";
        } else if (kendaraanMotor.isSelected()) {
            jenisKendaraan = "MOTOR";
        }

        if (jenisKendaraan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih jenis kendaraan (Mobil/Motor)!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int tarifDasar = Integer.parseInt(txtTarif.getText());

        if (platNomor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Plat Nomor wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jenisKendaraan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih jenis kendaraan (Mobil/Motor)!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String kodeTarif = kodeTarifAcak(jenisKendaraan);

        String sql = "INSERT INTO kendaraan (kode_tarif, plat_nomor, jenis_kendaraan, warna_kendaraan, "
                   + "tanggal_masuk, waktu_masuk, tarif, no_telp, petugas_jaga) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            java.sql.Connection conn = Koneksi.getConnection(); 
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, kodeTarif);
            ps.setString(2, platNomor);
            ps.setString(3, jenisKendaraan);
            ps.setString(4, warna);
            ps.setString(5, tanggalMasuk);
            ps.setString(6, waktuMasuk);
            ps.setInt(7, tarifDasar);
            ps.setString(8, telp);
            ps.setString(9, pilihPetugas);

            int hasil = ps.executeUpdate();

            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, "Kendaraan " + platNomor + " berhasil masuk! Kode Tiket: " + kodeTarif, "Sukses", JOptionPane.INFORMATION_MESSAGE);

                txtPlat.setText("");
                txtWarna.setText("");
                txtTlp.setText("");
                txtTarif.setText("");
                
                buttonGroup1.clearSelection(); 
                
                loadTable();
                
                javax.swing.JFrame frameInduk = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                if (frameInduk instanceof HalamanUtama) {
                    HalamanUtama hu = (HalamanUtama) frameInduk;

                    CetakKarcis panelCetak = new CetakKarcis(kodeTarif);
                    hu.pnlKonten.removeAll();
                    hu.pnlKonten.add(panelCetak);
                    hu.pnlKonten.repaint();
                    hu.pnlKonten.revalidate();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan ke database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void kendaraanMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kendaraanMotorActionPerformed
        // TODO add your handling code here:
        txtTarif.setText("2000");
        txtTarif.setEditable(false);
    }//GEN-LAST:event_kendaraanMotorActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtTlp.setText("");
        txtPlat.setText("");
        txtWarna.setText("");

        txtTarif.setText("");

        buttonGroup1.clearSelection();

        cbPetugas.setSelectedIndex(0); 

        txtTlp.requestFocus();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        String petugasAktif = cbPetugas.getSelectedItem().toString();
        
        HalamanUtama hu = new HalamanUtama(petugasAktif);
        hu.setVisible(true);

        javax.swing.JFrame frameInduk = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frameInduk != null) {
            frameInduk.dispose();
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPetugasActionPerformed
    public void loadTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        
        javax.swing.table.DefaultTableCellRenderer headerTengah = (javax.swing.table.DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer();
        headerTengah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.table.DefaultTableCellRenderer tengah = new javax.swing.table.DefaultTableCellRenderer();
        tengah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(tengah);
        }

        String sql = "SELECT * FROM kendaraan ORDER BY tanggal_masuk DESC, waktu_masuk DESC";

        try {
            java.sql.Connection conn = Koneksi.getConnection();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            java.sql.ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String platAsli = rs.getString("plat_nomor");
                String platFormat = platAsli;

                if (platAsli != null && platAsli.matches("^[A-Z]{1,2}\\d{1,4}[A-Z]{1,3}$")) {
                    platFormat = platAsli.replaceAll("^([A-Z]{1,2})(\\d{1,4})([A-Z]{1,3})$", "$1 $2 $3");
                }
                
                Object[] row = {
                    rs.getString("kode_tarif"),
                    rs.getString("no_telp"),
                    platFormat,
                    rs.getString("jenis_kendaraan"),
                    rs.getString("warna_kendaraan"),
                    rs.getString("tanggal_masuk"),
                    rs.getString("waktu_masuk"),
                    rs.getInt("tarif"),
                    rs.getString("petugas_jaga")
                };        
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data tabel: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton kendaraanMobil;
    private javax.swing.JRadioButton kendaraanMotor;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtPlat;
    private javax.swing.JTextField txtTarif;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtTlp;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
