/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Dearis Mahendra
 */
public class Laporan extends javax.swing.JPanel {

    /**
     * Creates new form LaporanKeuangan
     */
    public Laporan() {
        initComponents();
        tampilkanDataLaporan();
    }
    
    public void tampilkanDataLaporan() {
        String pilihan = cbJenisLaporan.getSelectedItem().toString();
        
        if (pilihan.equals("Jenis Laporan") || pilihan.isEmpty()) {
            scrollLaporan.setVisible(false);
            return;
        }
        
        String tglPilihan = "";
        if (dcTanggal.getDate() != null) {
            // Mengambil teks tanggal yang terformat otomatis dari JDateChooser
            tglPilihan = ((javax.swing.JTextField) dcTanggal.getDateEditor().getUiComponent()).getText();
        } else {
            // Kalau kalendernya belum dipilih kasir, otomatis pakai tanggal hari ini murni lek
            tglPilihan = java.time.LocalDate.now().toString();
        }
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        model.addColumn("Kode Tarif");
        model.addColumn("Plat Nomor");
        model.addColumn("Jenis Kendaraan");
        
        String sql = "";
        
        if (pilihan.contains("Masuk")) {
            model.addColumn("Tanggal Masuk");
            model.addColumn("Waktu Masuk");
            sql = "SELECT kode_tarif, plat_nomor, jenis_kendaraan, tanggal_masuk, waktu_masuk FROM data_kendaraan WHERE tanggal_masuk = ?";
            
        } else if (pilihan.contains("Keluar")) {
            model.addColumn("Tanggal Keluar");
            model.addColumn("Waktu Keluar");
            model.addColumn("Durasi");
            model.addColumn("Total Tarif");
            sql = "SELECT kode_tarif, plat_nomor, jenis_kendaraan, tanggal_keluar, waktu_keluar, durasi, total_tarif FROM riwayat_parkir WHERE status = 'Keluar' AND tanggal_keluar = ?";
            
        } else if (pilihan.contains("Kendaraan Karcis Hilang")) {
            model.addColumn("Tanggal Keluar");
            model.addColumn("Denda Karcis");
            sql = "SELECT kode_tarif, plat_nomor, jenis_kendaraan, tanggal_keluar, denda FROM riwayat_parkir WHERE denda > 0 AND tanggal_keluar = ?";
        }

        try {
            java.sql.Connection conn = Koneksi.getConnection();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, tglPilihan);
            java.sql.ResultSet rs = ps.executeQuery();            
            while (rs.next()) {
                if (pilihan.contains("Masuk")) {
                    model.addRow(new Object[]{
                        rs.getString("kode_tarif"), rs.getString("plat_nomor"),
                        rs.getString("jenis_kendaraan"), rs.getString("tanggal_masuk"), rs.getString("waktu_masuk")
                    });
                } else if (pilihan.contains("Keluar")) {
                    model.addRow(new Object[]{
                        rs.getString("kode_tarif"), rs.getString("plat_nomor"),
                        rs.getString("jenis_kendaraan"), rs.getString("tanggal_keluar"), rs.getString("waktu_keluar"),
                        rs.getString("durasi"), "Rp " + rs.getInt("total_tarif")
                    });
                } else if (pilihan.contains("Karcis Hilang")) {
                    model.addRow(new Object[]{
                        rs.getString("kode_tarif"), rs.getString("plat_nomor"),
                        rs.getString("jenis_kendaraan"), rs.getString("tanggal_keluar"), "Rp " + rs.getInt("denda")
                    });
                }
            }
            
            tabelLaporan.setModel(model);
            scrollLaporan.setVisible(true);
            
            scrollLaporan.revalidate();
            scrollLaporan.repaint();
            this.revalidate();
            this.repaint();
            
            rs.close();
            ps.close();
        } catch (Exception e) {
            System.out.println("Gagal load database laporan: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbJenisLaporan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        scrollLaporan = new javax.swing.JScrollPane();
        tabelLaporan = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        dcTanggal = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Laporan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(441, 441, 441))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbJenisLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Laporan", "Kendaraan Masuk", "Kendaraan Keluar", "Kendaraan Karcis Hilang" }));
        cbJenisLaporan.addActionListener(this::cbJenisLaporanActionPerformed);

        tabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollLaporan.setViewportView(tabelLaporan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollLaporan)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        dcTanggal.setDateFormatString("yyyy-MM-dd");
        dcTanggal.addPropertyChangeListener(this::dcTanggalPropertyChange);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKembali)))
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void cbJenisLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisLaporanActionPerformed
        // TODO add your handling code here:
        tampilkanDataLaporan();
    }//GEN-LAST:event_cbJenisLaporanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        javax.swing.JFrame frameInduk = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frameInduk instanceof HalamanUtama) {
            HalamanUtama hu = (HalamanUtama) frameInduk;
            hu.pnlKonten.removeAll();
            hu.pnlKonten.repaint();
            hu.pnlKonten.revalidate();
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void dcTanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcTanggalPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            tampilkanDataLaporan();
        }
    }//GEN-LAST:event_dcTanggalPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbJenisLaporan;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollLaporan;
    private javax.swing.JTable tabelLaporan;
    // End of variables declaration//GEN-END:variables
}
