/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Dearis Mahendra
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class LogAktivitas extends javax.swing.JPanel {

    /**
     * Creates new form LogAktivitas
     */
    public LogAktivitas() {
        initComponents();
        loadAktivitasDinamis("");
    }
    
    public void loadAktivitasDinamis(String kataKunci) {
        pnlScroll.removeAll();

        // Query ambil data & format bulan 3 huruf cth: Jun, Mei, Apr
        String sql = "SELECT DATE_FORMAT(tanggal, '%d %b %Y') AS tgl_format, "
                   + "DATE_FORMAT(tanggal, '%M %Y') AS bulan_tahun, "
                   + "jam, petugas, status, kode_tarif FROM log_aktivitas ";
        
        if (!kataKunci.isEmpty()) {
            sql += "WHERE status LIKE ? OR petugas LIKE ? OR kode_tarif LIKE ? ";
        }
        sql += "ORDER BY tanggal DESC, jam DESC";

        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            if (!kataKunci.isEmpty()) {
                ps.setString(1, "%" + kataKunci + "%");
                ps.setString(2, "%" + kataKunci + "%");
                ps.setString(3, "%" + kataKunci + "%");
            }
            ResultSet rs = ps.executeQuery();
            String bulanSebelumnya = "";

            while (rs.next()) {
                String bulanSekarang = rs.getString("bulan_tahun"); 
                String status = rs.getString("status");
                String tglFormat = rs.getString("tgl_format");
                String waktu = rs.getString("jam").substring(0, 5);
                String petugas = rs.getString("petugas");
                String kodeTarif = rs.getString("kode_tarif");
                
                String tglWaktuGabung = tglFormat + " - " + waktu + " | Oleh " + petugas;

                if (!bulanSekarang.equals(bulanSebelumnya)) {
                    String bulanIndo = bulanSekarang.replace("June", "Juni")
                                                    .replace("May", "Mei")
                                                    .replace("April", "April")
                                                    .replace("March", "Maret")
                                                    .replace("February", "Februari")
                                                    .replace("January", "Januari");
                    
                    HeaderBulan pnlBulan = new HeaderBulan(bulanIndo);
                    pnlScroll.add(pnlBulan);
                    
                    bulanSebelumnya = bulanSekarang;
                }
                
                String jenisAksi = "Keluar";
                if (status.toLowerCase().contains("masuk") || status.toLowerCase().contains("parkir masuk")) {
                    jenisAksi = "Masuk";
                }

                ItemLog item = new ItemLog(status, tglWaktuGabung, kodeTarif, jenisAksi);
                pnlScroll.add(item);
            }
            rs.close();
            ps.close();

            pnlScroll.revalidate();
            pnlScroll.repaint();

        } catch (Exception e) {
            System.out.println("Gagal load log aktivitas: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCariAktivitas = new javax.swing.JTextField();
        btnCariAktivitas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlScroll = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 390));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(537, 33));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Log Aktivitas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnCariAktivitas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCariAktivitas.setText("Cari");
        btnCariAktivitas.addActionListener(this::btnCariAktivitasActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cari Aktivitas");

        pnlScroll.setBackground(new java.awt.Color(204, 204, 255));
        pnlScroll.setLayout(new javax.swing.BoxLayout(pnlScroll, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlScroll);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCariAktivitas)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(437, 437, 437))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariAktivitas)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        javax.swing.JFrame frameInduk = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frameInduk instanceof HalamanUtama) {
            HalamanUtama hu = (HalamanUtama) frameInduk;
            hu.pnlKonten.removeAll();
            
            hu.pnlKonten.repaint();
            hu.pnlKonten.revalidate();
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCariAktivitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariAktivitasActionPerformed
        // TODO add your handling code here:
        loadAktivitasDinamis(txtCariAktivitas.getText().trim());
    }//GEN-LAST:event_btnCariAktivitasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariAktivitas;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlScroll;
    private javax.swing.JTextField txtCariAktivitas;
    // End of variables declaration//GEN-END:variables
}
