/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ROHMAN
 */
import javax.swing.JOptionPane;
public class ParkirKeluar extends javax.swing.JPanel {
    private long totalJamGlobal = 0;
    private int tarifPerJamGlobal = 0;
    private String jenisKendaraanGlobal = "";
    /**
     * Creates new form CetakKarcis
     */
    public ParkirKeluar() {
        initComponents();
    }
    
    public ParkirKeluar(String kodeOtomatis) {
        initComponents();
        txtCariData.setText(kodeOtomatis);
        btnCariPlatActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariData = new javax.swing.JTextField();
        btnCariPlat = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtPlat = new javax.swing.JTextField();
        txtJenisKendaraan = new javax.swing.JTextField();
        txtWarna = new javax.swing.JTextField();
        txtTarif = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtJamMasuk = new javax.swing.JTextField();
        txtJamKeluar = new javax.swing.JTextField();
        txtTglMasuk = new javax.swing.JTextField();
        txtTotalJam = new javax.swing.JTextField();
        txtPetugas = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTglKeluar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        cbPetugasKeluar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        chkKarcisHilang = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(950, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(524, 33));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Kendaraan Keluar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(397, 397, 397))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Plat Nomer");

        txtCariData.addActionListener(this::txtCariDataActionPerformed);

        btnCariPlat.setBackground(new java.awt.Color(204, 204, 255));
        btnCariPlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCariPlat.setText("Cari");
        btnCariPlat.addActionListener(this::btnCariPlatActionPerformed);

        btnKeluar.setBackground(new java.awt.Color(204, 204, 255));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        btnKembali.setBackground(new java.awt.Color(204, 204, 255));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kode Tarif");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Plat Nomer");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jenis Kendaraan");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Warna Kendaraan");

        txtKode.setEditable(false);
        txtKode.addActionListener(this::txtKodeActionPerformed);

        txtPlat.setEditable(false);
        txtPlat.addActionListener(this::txtPlatActionPerformed);

        txtJenisKendaraan.setEditable(false);
        txtJenisKendaraan.addActionListener(this::txtJenisKendaraanActionPerformed);

        txtWarna.setEditable(false);
        txtWarna.addActionListener(this::txtWarnaActionPerformed);

        txtTarif.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tarif");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal Masuk");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Jam Keluar");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Jam Masuk");

        txtJamMasuk.setEditable(false);
        txtJamMasuk.addActionListener(this::txtJamMasukActionPerformed);

        txtJamKeluar.setEditable(false);
        txtJamKeluar.addActionListener(this::txtJamKeluarActionPerformed);

        txtTglMasuk.setEditable(false);
        txtTglMasuk.addActionListener(this::txtTglMasukActionPerformed);

        txtTotalJam.setEditable(false);

        txtPetugas.setEditable(false);
        txtPetugas.addActionListener(this::txtPetugasActionPerformed);

        txtTotalBayar.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Total Jam");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Total Tarif");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Tanggal Keluar");

        txtTglKeluar.addActionListener(this::txtTglKeluarActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nama Petugas Masuk");

        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel12))
                            .addComponent(txtPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtJamMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(txtTglMasuk, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtTotalJam, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtTglKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJamKeluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(btnHitung, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTglKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHitung)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cbPetugasKeluar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Petugas", "Dearis", "Khabid", "Rohman" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Nama Petugas Keluar");

        chkKarcisHilang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkKarcisHilang.setText("Karcis Hilang");
        chkKarcisHilang.addActionListener(this::chkKarcisHilangActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(chkKarcisHilang)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCariPlat)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbPetugasKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(btnKeluar)
                .addGap(147, 147, 147)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPlat)
                    .addComponent(jLabel15)
                    .addComponent(cbPetugasKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkKarcisHilang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addComponent(btnKeluar))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariDataActionPerformed

    private void btnCariPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPlatActionPerformed
        // TODO add your handling code here:
        String platCari = txtCariData.getText().trim().toUpperCase().replace(" ", "");

        if (platCari.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukan Plat Nomor Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "SELECT * FROM data_kendaraan WHERE REPLACE(plat_nomor, ' ', '') = ?";

        try {
            java.sql.Connection conn = Koneksi.getConnection();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, platCari);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String kode = rs.getString("kode_tarif");
                String platInput = rs.getString("plat_nomor");
                String platFormat = platInput;
                
                if (platInput != null) {
                    platInput = platInput.trim().toUpperCase().replace(" ", "");
                    
                    if (platInput.matches("^[A-Z]{1,2}\\d+[A-Z]{1,3}$")) {
                        platFormat = platInput.replaceAll("^([A-Z]{1,2})(\\d+)([A-Z]{1,3})$", "$1 $2 $3");
                    }
                }
                
                String jenis = rs.getString("jenis_kendaraan");
                String warna = rs.getString("warna_kendaraan");
                String tglMasukStr = rs.getString("tanggal_masuk");
                String jamMasukStr = rs.getString("jam_masuk");
                int tarifPerJam = rs.getInt("tarif");
                String petugas = rs.getString("petugas_jaga");

                // Logika Hitung Waktu Parkir Realtime
                java.time.LocalDate tglMasuk = java.time.LocalDate.parse(tglMasukStr);
                java.time.LocalTime jamMasuk = java.time.LocalTime.parse(jamMasukStr);
                java.time.LocalDateTime waktuAwal = java.time.LocalDateTime.of(tglMasuk, jamMasuk);
                
                // WAKTU SISTEM REALTIME HARI INI
                java.time.LocalDateTime waktuAkhir = java.time.LocalDateTime.now();
                String jamKeluarStr = waktuAkhir.toLocalTime().format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss"));
                String tglKeluarStr = waktuAkhir.toLocalDate().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"));

                // Hitung durasi jam
                long selisihMenit = java.time.temporal.ChronoUnit.MINUTES.between(waktuAwal, waktuAkhir);
                long totalJam = (long) Math.ceil(selisihMenit / 60.0);
                if (totalJam <= 0) totalJam = 1; // Minimal bayar 1 jam

                totalJamGlobal = totalJam;
                tarifPerJamGlobal = tarifPerJam;
                jenisKendaraanGlobal = jenis;

                txtKode.setText(kode);
                txtJenisKendaraan.setText(jenis);
                txtTglMasuk.setText(tglMasukStr);
                txtTglKeluar.setText(tglKeluarStr);
                txtPetugas.setText(petugas);

                txtWarna.setText(warna);
                txtJamMasuk.setText(jamMasukStr);
                txtTotalJam.setText(totalJam + " Jam");

                txtPlat.setText(platFormat);
                txtTarif.setText("Rp. " + tarifPerJam);
                txtJamKeluar.setText(jamKeluarStr);

                txtTarif.setText("Rp. " + tarifPerJam);
                txtTotalBayar.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Plat Nomor " + txtCariData.getText() + " tidak ditemukan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                bersihkanForm();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal koneksi database lek: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCariPlatActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        if (txtKode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cari data plat nomor kendaraan yang valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String petugasKeluar = cbPetugasKeluar.getSelectedItem().toString();
        if (petugasKeluar.equals("Pilih Petugas")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih nama Petugas Kelur!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String platCari = txtCariData.getText().trim().toUpperCase().replace(" ", "");
        String petugasMasuk = txtPetugas.getText();
        
        String jamKeluarStr = txtJamKeluar.getText();
        java.time.LocalDate tanggalHariIni = java.time.LocalDate.now();
        String tglKeluarStr = tanggalHariIni.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        
        String pesanSukses = "Pembayaran Sukses!\n\n"
                           + "Detail Konfirmasi:\n"
                           + "- Disahkan Masuk Oleh : " + petugasMasuk + "\n"
                           + "- Disahkan Keluar Oleh : " + petugasKeluar + "\n\n"
                           + "- Tanggal Keluar : " + tglKeluarStr + "\n"
                           + "- Jam Keluar : " + jamKeluarStr + "\n\n"
                           + "Data log lengkap berhasil disimpan & kendaraan diizinkan keluar!";;

        String sqlDelete = "DELETE FROM data_kendaraan WHERE REPLACE(plat_nomor, ' ', '') = ?";

        try {
            java.sql.Connection conn = Koneksi.getConnection();
            
            String sqlAmbil = "SELECT * FROM data_kendaraan WHERE REPLACE(plat_nomor, ' ', '') = ?";
            java.sql.PreparedStatement psAmbil = conn.prepareStatement(sqlAmbil);
            psAmbil.setString(1, platCari);
            java.sql.ResultSet rs = psAmbil.executeQuery();
            
            if (rs.next()) {
                String kode = rs.getString("kode_tarif");
                String plat = rs.getString("plat_nomor");
                String jenis = rs.getString("jenis_kendaraan");
                String warna = rs.getString("warna_kendaraan");
                String tglMasuk = rs.getString("tanggal_masuk");
                String jmMasuk = rs.getString("jam_masuk");
                int tarifDasar = rs.getInt("tarif");
                String petMasuk = rs.getString("petugas_jaga");
                
                int totBayar = Integer.parseInt(txtTotalBayar.getText().replace("Rp. ", "").trim());
                String durasiParkir = txtTotalJam.getText().trim();
                
                int nilaiDenda = 0;
                if (chkKarcisHilang.isSelected()) {
                    nilaiDenda = jenis.equalsIgnoreCase("Motor") ? 25000 : 50000;
                }

                String sqlInsertRiwayat = "INSERT INTO riwayat_parkir (kode_tarif, plat_nomor, jenis_kendaraan, warna_kendaraan, "
                        + "tanggal_masuk, jam_masuk, tanggal_keluar, jam_keluar, tarif, petugas_jaga, petugas_keluar, durasi, total_tarif, denda, status) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                
                java.sql.PreparedStatement psArsip = conn.prepareStatement(sqlInsertRiwayat);
                psArsip.setString(1, kode);
                psArsip.setString(2, plat);
                psArsip.setString(3, jenis);
                psArsip.setString(4, warna);
                psArsip.setString(5, tglMasuk);
                psArsip.setString(6, jmMasuk);
                psArsip.setString(7, tglKeluarStr);
                psArsip.setString(8, jamKeluarStr);
                psArsip.setInt(9, tarifDasar);
                psArsip.setString(10, petMasuk);
                psArsip.setString(11, petugasKeluar);
                psArsip.setString(12, durasiParkir);
                psArsip.setInt(13, totBayar);
                psArsip.setInt(14, nilaiDenda);
                psArsip.setString(15, "Keluar");
                psArsip.executeUpdate();
                psArsip.close();
            }
            
            java.sql.PreparedStatement ps = conn.prepareStatement(sqlDelete);
            ps.setString(1, platCari);
            int suksesHapus = ps.executeUpdate();

            if (suksesHapus > 0) {
                String sqlLogManual = "INSERT INTO log_aktivitas (tanggal, jam, petugas, status, kode_tarif) VALUES (?, ?, ?, ?, ?)";
                try (java.sql.PreparedStatement psLog = conn.prepareStatement(sqlLogManual)) {
                    psLog.setString(1, tglKeluarStr);
                    psLog.setString(2, jamKeluarStr);
                    psLog.setString(3, petugasKeluar);
                    psLog.setString(4, "Kendaraan Keluar");
                    psLog.setString(5, txtKode.getText());
                    psLog.executeUpdate();
                } catch (Exception exLog) {
                    System.out.println("Gagal kueri log_aktivitas keluar: " + exLog.getMessage());
                }
                
                Koneksi.catatAktivitas(petugasKeluar, "Kendaraan Keluar", txtKode.getText());
                JOptionPane.showMessageDialog(this, pesanSukses, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                bersihkanForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data kendaraan dari sistem!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        String petugasAktif = cbPetugasKeluar.getSelectedItem().toString();
    
        if (petugasAktif.equals("Pilih Petugas")) {
            petugasAktif = txtPetugas.getText();
        }

        if (petugasAktif.isEmpty()) {
            petugasAktif = "Petugas"; 
        }

        HalamanUtama hu = new HalamanUtama(petugasAktif);
        hu.setVisible(true);

        javax.swing.JFrame frameInduk = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (frameInduk != null) {
            frameInduk.dispose();
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void txtPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlatActionPerformed

    private void txtJenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisKendaraanActionPerformed

    private void txtJamMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamMasukActionPerformed

    private void txtJamKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamKeluarActionPerformed

    private void txtTglMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglMasukActionPerformed

    private void txtWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarnaActionPerformed

    private void txtTglKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglKeluarActionPerformed

    private void txtPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPetugasActionPerformed

    private void chkKarcisHilangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKarcisHilangActionPerformed
        // TODO add your handling code here:
        if (!txtCariData.getText().isEmpty()) {
            btnCariPlatActionPerformed(null);
        }
    }//GEN-LAST:event_chkKarcisHilangActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        if (txtKode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan cari plat nomor kendaraan yang valid terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long totalBayar = totalJamGlobal * tarifPerJamGlobal;
        
        if (chkKarcisHilang.isSelected()) {
            int nominalDenda = jenisKendaraanGlobal.equalsIgnoreCase("Motor") ? 25000 : 50000;
            totalBayar += nominalDenda;
        }

        txtTarif.setText("Rp. " + tarifPerJamGlobal);
        txtTotalBayar.setText("Rp. " + totalBayar);
    }//GEN-LAST:event_btnHitungActionPerformed
    private void bersihkanForm() {
        txtCariData.setText("");
        txtPetugas.setText("");
        txtKode.setText("");
        txtJenisKendaraan.setText("");
        txtWarna.setText("");
        txtTglMasuk.setText("");
        txtJamMasuk.setText("");
        txtJamKeluar.setText("");
        txtTglKeluar.setText("");
        txtTotalJam.setText("");
        txtPlat.setText("");
        txtTarif.setText("");
        txtTotalBayar.setText("");
        cbPetugasKeluar.setSelectedIndex(0);
        txtCariData.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariPlat;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbPetugasKeluar;
    private javax.swing.JCheckBox chkKarcisHilang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCariData;
    private javax.swing.JTextField txtJamKeluar;
    private javax.swing.JTextField txtJamMasuk;
    private javax.swing.JTextField txtJenisKendaraan;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtPetugas;
    private javax.swing.JTextField txtPlat;
    private javax.swing.JTextField txtTarif;
    private javax.swing.JTextField txtTglKeluar;
    private javax.swing.JTextField txtTglMasuk;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtTotalJam;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
